### ISSUE TITLE
async functions show return lines as not being covered from a branch perspective

### ISSUE THREAD

**Issue by mikecbrant** [bcoe/c8#135] opened 2019-08-23 15:13 UTC
* **5.0.1**:
* **Windows 10 / Node 12.6.0 with --experimental-modules / tap 14.6.1**:

We are finding ourselves needing to always inject `/* c8 ignore next */` in our async functions in order to get passing coverage results.  I have included sample code below.

Typical command line usage would be `c8 tap` (oftentimes with --check-coverage flags as well).

It should be noted that these cases where we find this behavior are all in Node --experimental-modules environments where we are using the ES modules format. (This is actually what led us to use c8 / tap in the first place as it they play nicely with native ESModules without need for ESM loader or similar)

There seem to be two different scenarios where branch covereage reporting is problematic.

case 1 - standard function return 
```
async function () {
    // some code
   return; // must ignore this line to get branch coverage
};
```

case 2 - then() function
```
const value = await someThenable()
  .then( (data) => {
     // do something;
    return data;
  }); // must ignore this line to get branch coverage
```

** Sample code under test**

I can get 100% branch coverage on this file only with each async function return ignored from coverage reports as shown.

```
import mongo from 'mongodb';
const { ObjectID } = mongo;

const getRecord = () => {
  return {
    _id: ObjectID(),
    created: new Date()
  };
};

class MockCollection {
  constructor(opts) {
    this._failKeys = new Set(opts.failKeys);
    this._notFoundKeys = new Set(opts.notFoundKeys);
    this._keyAccessCounts = {};
  }

  _action(key) {
    if (!this._keyAccessCounts.hasOwnProperty(key)) {
      this._keyAccessCounts[key] = 0;
    }
    this._keyAccessCounts[key]++;

    if (this._failKeys.has(key) ) {
      throw new Error(`mock error on key '${key}'`);
    }

    return ( this._notFoundKeys.has(key) ) ? false : true;
  }

  _getKeyAccessCounts(key) {
    return (key) ? this._keyAccessCounts[key] : this._keyAccessCounts;
  }

  async createIndex(keys, opts) {
    this._action('createIndex');

    const parts = [
      'mock',
      Object.keys(keys)
        .reduce( (str, key) => `${str}_${key}_${keys[key]}`, '' )
        // trim leading '_'
        .slice(1)
    ];

    if (opts) {
      parts.push( Object.keys(opts).join('_') );
    }

    /* c8 ignore next */
    return parts.join('_');
  }

  async find() {
    const recordCount = 100;
    const records = [];

    if (this._action('find')) {
      for (let i = 0; i < recordCount; i++) records.push(getRecord());
    }

    /* c8 ignore next */
    return new MockCursor(records);
  }

  async findOne() {
    /* c8 ignore next */
    return (this._action('findOne')) ? getRecord() : null;
  }

  async insertOne() {
    this._action('insertOne');
    /* c8 ignore next */
    return getRecord();
  }

  async updateOne() {
    let result = {
      modifiedCount: 1,
      matchedCount: 1
    };
    const succeeded = this._action('updateOne');
    if (!succeeded) {
      result = {
        modifiedCount: 0,
        matchedCount: 0
      };
    }
    /* c8 ignore next */
    return result;
  }
}

class MockCursor {
  constructor(records) {
    this._records = records;
    this._offset = 0;
    this._limit = 0;
  }

  limit(limit) {
    this._limit = limit;
    return this;
  }

  sort() {
    // not implemented
    return this;
  }

  skip(offset) {
    this._offset = offset;
    return this;
  }

  async toArray() {
    const offset = this._offset;
    const limit = this._limit;
    const end = (limit > 0) ? offset + limit : undefined;
    /* c8 ignore next */
    return this._records.slice(offset, end);
  }
}

class MockDb {
  constructor(opts) {
    this._opts = opts;
    this._collections = {};
  }

  collection(name) {
    if (!this._collections.hasOwnProperty(name)) {
      const opts = {
        failKeys: this._opts.failConfig[name] || [],
        notFoundKeys: this._opts.notFoundConfig[name] || [],
      };
      this._collections[name] = new MockCollection(opts);
    }
    return this._collections[name];
  }
}


/*
The config passed to MockMongoClient allows us to configure failure (thrown errors)
and/or not found behavior from methods called on given collection. The object may look like the following...

{
  failConfig: {
    clientAccounts: ['findOnce']
  },
  notFoundConfig: {
    clientAccounts: ['updateOne']
  }
}

... where the keys for each config objecg specify a mongo collection name and the arrays at each keys represent ths
*/

const defaultOpts = {
  failConfig: {},
  notFoundConfig: {}
};

class MockMongoClient {
  constructor(opts) {
    opts = opts || {};
    this._opts = Object.assign({}, defaultOpts, opts);
    this._db = null;
  }

  db() {
    if (!this._db) {
      this._db = new MockDb(this._opts);
    }
    return this._db;
  }
}

const getMockMongoClient = (opts) => new MockMongoClient(opts);

export {
  getMockMongoClient as default,
  MockCollection,
  MockCursor,
  MockDb,
  MockMongoClient,
  ObjectID
};
```

**Comment by mikecbrant** [comment] 2019-10-02 14:45
Sorry, I missed your request for more info.  

Having thought about this issue some more, I don't know that this is **technically** a bug, as any async function will have two branches - one for the `resolve` case (a normal return) and one for the `reject` case.  Perhaps this is what is causing the branch to be noted as uncovered.

The only problem with this is that in many cases, it might be burdensome or impossible to exercise both resolve and reject paths during testing, especially if the reject path might be triggered by code outside of the code under test (i.e. a third party client library service call that may reject or similar).

Anyway, I am copying output from tests below.

---------------------------------------------------

Successful test, with ignores in place as shown in my code example above.

```
info: Starting 'executeTests'...
test/main.test.mjs 2> (node:4700) ExperimentalWarning: The ESM module loader is experimental.
test/lib/MockMongoClient.test.mjs 2> (node:71248) ExperimentalWarning: The ESM module loader is experimental.
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://localhost:27017/'
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://somehost:27017,otherhost:27017/'
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://localhost:27017/'
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://localhost:27017/'
test/main.test.mjs 1> info: instantiating MockMongoClient
 PASS  test/main.test.mjs 9 OK 4s
 PASS  test/lib/MockMongoClient.test.mjs 19 OK 4s

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   2 passed, 2 of 2 completed
Asserts:  28 passed, of 28
Time:     4s
----------------------|----------|----------|----------|----------|-------------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------|----------|----------|----------|----------|-------------------|
All files             |      100 |      100 |      100 |      100 |                   |
 mongo                |      100 |      100 |      100 |      100 |                   |
  index.mjs           |      100 |      100 |      100 |      100 |                   |
 mongo/lib            |      100 |      100 |      100 |      100 |                   |
  MockMongoClient.mjs |      100 |      100 |      100 |      100 |                   |
----------------------|----------|----------|----------|----------|-------------------|
info: Finished 'executeTests' after 9s
```

Failing test, after I have removed all my ignore comments, note we are now failing branch coverage at the 5 places I removed the ignores.

```
info: Starting 'executeTests'...
test/main.test.mjs 2> (node:72584) ExperimentalWarning: The ESM module loader is experimental.
test/lib/MockMongoClient.test.mjs 2> (node:4144) ExperimentalWarning: The ESM module loader is experimental.
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://localhost:27017/'
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://somehost:27017,otherhost:27017/'
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://localhost:27017/'
test/main.test.mjs 1> info: Instantiating new MongoClient using URI 'mongodb://localhost:27017/'
test/main.test.mjs 1> info: instantiating MockMongoClient
 PASS  test/main.test.mjs 9 OK 3s
 PASS  test/lib/MockMongoClient.test.mjs 19 OK 3s

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   2 passed, 2 of 2 completed
Asserts:  28 passed, of 28
Time:     3s
----------------------|----------|----------|----------|----------|-------------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------|----------|----------|----------|----------|-------------------|
All files             |      100 |    92.86 |      100 |      100 |                   |
 mongo                |      100 |      100 |      100 |      100 |                   |
  index.mjs           |      100 |      100 |      100 |      100 |                   |
 mongo/lib            |      100 |     89.8 |      100 |      100 |                   |
  MockMongoClient.mjs |      100 |     89.8 |      100 |      100 |    50,61,65,70,85 |
----------------------|----------|----------|----------|----------|-------------------|
ERROR: Coverage for branches (92.86%) does not meet global threshold (100%)
error: 'executeTests' errored after 6s
{
  "data": {
    "message": "shellPromise child process exited with code 1",
    "name": "Error",
    "stack": "Error: shellPromise child process exited with code 1\n    at ChildProcess.<anonymous> (file:///C:/Users/mbrant/git/mongo/node_modules/@ignitesales/gulpish-util/index.mjs:37:16)\n    at ChildProcess.emit (events.js:209:13)\n    at ChildProcess.EventEmitter.emit (domain.js:499:23)\n    at maybeClose (internal/child_process.js:1021:16)\n    at
Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)"
  }
}
Error: shellPromise child process exited with code 1
    at ChildProcess.<anonymous> (file:///C:/Users/mbrant/git/mongo/node_modules/@ignitesales/gulpish-util/index.mjs:37:16)
    at ChildProcess.emit (events.js:209:13)
    at ChildProcess.EventEmitter.emit (domain.js:499:23)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm ERR! Test failed.  See above for more details.
```

**Comment by bcoe** [comment] 2019-10-24 05:57
@mikecbrant does this continue to be an issue with Node 13, there have been a variety of fixes upstream in V8.

**Comment by mikecbrant** [comment] 2019-10-24 22:18
I don’t know yet. I am kind of stuck to node 12.10 right now due to an unrelated issue with Esm package used by some of our devops dependencies. Was planning to install node 13 in next day or two to see if that issue perhaps goes away as well. If I get that working I will let you know if this changes any behavior with c8

**Comment by mikecbrant** [comment] 2019-10-28 18:40
I am still seeing this in Node 13.0.1.

**Comment by bcoe** [comment] 2019-11-30 22:06
@mikecbrant could you provide a minimal reproduction, either in a separate repo or source-code you provide here?

**Comment by maxwell-k** [comment] 2020-01-08 18:48
I may have also come across this "bug".

As I was coming up with a minimal reproducible example I noticed a mistake in my code: a function was marked as `async` when it only returns a promise and does not need to be declared as async.

If I don't mark the function as `async` this "bug" disappears.

It is still strange that the output shows 100% line coverage but only 75% branch coverage.

<details>
<summary>Minimal reproducible example with unnecessary async function declaration</summary>

First some initial setup:

```
$ node --version
v13.1.0
$ mkdir test
$ npm install c8 mocha
✂
+ mocha@7.0.0
+ c8@7.0.0
✂
```

Then add two files, first `main.js`:

```javascript
module.exports = async function() {
  return new Promise(function(resolve) {
    resolve(1);
  });
};
```

Then `test/test.js`:

```javascript
const assert = require("assert");
const one = require("../main.js");

describe("Example", async function() {
  it("Showing return line not covered", async function() {
    assert.equal(1, await one());
  });
});
```

```
$ npx c8 mocha


  Example
    ✓ Showing return line not covered


  1 passing (12ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |       75 |     100 |     100 |
 main.js  |     100 |       75 |     100 |     100 | 4
----------|---------|----------|---------|---------|-------------------
```

</details>

**Comment by maxwell-k** [comment] 2020-01-09 11:19
I've looked at this again and can confirm I can reproduce this issue; I will update the comment above in place rather than complicate things. Sorry for any confusion my comment yesterday may have added.

**Comment by maxwell-k** [comment] 2020-02-24 09:06
I added the example above to https://github.com/maxwell-k/c8-issue-135 in case that makes this easier to investigate.

Can reproduce on Node v12.15.0

@bcoe does the example work for you?

**Comment by bcoe** [comment] 2020-02-26 06:57
@maxwell-k 👍 thanks for the reproduction. I'd be surprised if this didn't turn out to be an issue in V8, I'll open an upstream trac king issue.

**Comment by dbarnespaychex** [comment] 2020-05-08 18:15
Just wanted to add to the conversation.

I'm not seeing this particular issue with _all_ async functions. Instead, in my code, it's always the closing brace of a `try/catch/finally` block within an async function that gets reported as a covered line but an uncovered branch:

```js
async function abc() {
  try {
    return 'abc';
  } finally {
    console.log('in finally');
  } // this is a covered line but uncovered branch
}
```

```js
async function badMath() {
  try {
    return 5 / 0;
  } catch (e) {
    console.error(e);
  } // this is a covered line but uncovered branch
}
```
Is V8 maybe adding some kind of hidden conditional at the end of a `try` block inside an async function that gets misreported as an uncovered branch?

**Comment by mikecbrant** [comment] 2020-06-05 01:29
@dbarnespaychex 

Your examples kind of support my theory that c8 always showing last line of async function as uncovered if there is no exercise of the rejection path. In both of your examples your functions’ async promises will always resolve and never reject,  therefore there is no way for you to ever even test the rejection path. 

For these cases, it seems like c8 just flags the last line as uncovered. It would be interesting to see if you added an additional line your functions after the try-catch-finally block whether that line would then be shown as uncovered from a branch perspective.

**Comment by dbarnespaychex** [comment] 2020-06-05 12:46
@mikecbrant 

I thought for sure you must be right, but I checked my code against my unit tests and am definitely testing the rejection path.

For example, here is some real code (some logic redacted) showing that some branch wasn't covered:

![image](https://user-images.githubusercontent.com/7923345/83875790-bd403c00-a705-11ea-8d9d-258780d201be.png)

And here are my unit tests:
```
      withUncaughtExceptionHandling
        √ ignores non-exceptions
        √ rethrows auth errors
        √ tracks errors
        √ redirects IGNORE severities to <redacted>
        √ removes any existing responses
        √ does not return <redacted>
        √ returns <redacted> if debug enabled
        √ closes <redacted> if FATAL
```

So I feel like I'm testing all the scenarios.

I did add another line afterwards to see if it was covered and it showed as an uncovered statement:

![image](https://user-images.githubusercontent.com/7923345/83876288-9f270b80-a706-11ea-8492-c2231c8aa17b.png)

That makes sense because I'm either returning or throwing an exception earlier in the function. However, switching to this provides full coverage:

![image](https://user-images.githubusercontent.com/7923345/83877106-f4175180-a707-11ea-915b-59dcc663bfbc.png)

I would never expect a `throw` inside a try/catch inside an async function to show the final try/catch brace as covered. After all, execution has halted and the stack is unwound immediately. But it seems as if V8 _also_ doesn't see a return statement inside a try/catch as covering the final brace -- but only when inside an async function.

Until this is fixed, I suppose I can switch all of my code to use this more verbose return syntax, but that will quickly become a real pain. And I'm worried there may be some subtle -- but critical -- 
difference between this:

```js
async function abc() {
  try {
    return 'abc';
  } finally {
  }
}
```
and this:
```js
async function abc() {
  let result;
  try {
    result = 'abc';
  } finally {
  }
  return result;
}

**Comment by dbarnespaychex** [comment] 2020-06-05 13:22
Just noticed this also happens inside a switch statement inside an async function, so I don't believe this is specific to try/catch.
```js
async function abc(arg) {
  switch (arg) {
    case 1:
      return 'abc';
    default:
      return 'something else';
  } // <-- shows as uncovered
}
```

**Comment by bcoe** [comment] 2020-06-05 23:09
@dbarnespaychex what version of Node.js are you using? There have been a variety of bugs fixed upstream in v8 related to this (some can bugs are addressed in Node 12/Node 14, which would still be present in Node 10).

I wouldn't be shocked if there still are some bugs in V8, and we should open an issue on the upstream issue tracker.

**Comment by dbarnespaychex** [comment] 2020-06-08 12:14
```bash
$ node -v
v14.2.0
```

**Comment by mikeal** [comment] 2020-06-11 19:40
Still seeing `v12.8.0` as well.

**Comment by mikeal** [comment] 2020-06-11 19:47
When I run with `—reporter=html` the page doesn’t show any missing branch coverage in the detail page. This makes me think that this is probably fixable via a workaround in `c8`. I suspect that you could look into the coverage data before surfacing the final % coverage and factor this out.

`c8` is the only way to do coverage w/ native ESM. Now that ESM is unflagged in Node.js LTS, issues like this are going to be standing in the way of ESM adoption. This makes me think it isn’t sufficient to say “this is an upstream v8 bug.” Working around issues in the underlying platform is pretty common and the need for `c8` to work reliably has been greatly increased with ESM being unflagged.

**Comment by bcoe** [comment] 2020-06-12 03:42
@mikeal @dbarnespaychex the way to debug one of these issues, such that I can create an upstream report is as follows.

I create a file with example code, like this:

**foo.js**

```js
async function abc() {
  try {
    return 'abc';
  } finally {
    console.log('in finally');
  } // this is a covered line but uncovered branch
}

abc()
```

I run the file with c8, `./bin/c8.js foo.js`.

I look at the output in `coverage/tmp/coverage-xyz.json`, for the function ABC. This is the raw output from V8.

In the provided example this is what I see:

```json
       {
          "functionName": "abc",
          "ranges": [
            {
              "startOffset": 0,
              "endOffset": 146,
              "count": 1
            },
            {
              "startOffset": 97,
              "endOffset": 145,
              "count": 0
            }
          ],
          "isBlockCoverage": true
        }
}
```

☝️ what this tells me is that V8 is treating characters `97 - 145` as a distinct block that is not executed.... the problem is that this is the following line:

```
'// this is a covered line but uncovered branch\n
```

☝️ this would appear to definitely be a V8 bug, and since c8 is dumb (it doesn't parse the JavaScript AST), the cleanest fix is to probably keep reporting these issues to V8.

---

@victorgomes I don't suppose you could help us on the V8 side? as @mikeal points out, v8's coverage has become pretty important to the Node ecosystem since ESM went live.

**Comment by bcoe** [comment] 2020-06-19 23:10
I am closing this issue in favor of:

https://github.com/bcoe/c8/issues/229

There is a corresponding issue now opened on v8.

As we find specific examples like #229, I will continue to open tracking issues.

**Closed by bcoe** 2020-06-19 23:10 UTC
Labels: bug, more-info-needed, v8

**Comment by mikeal** [comment] 2020-06-20 01:07
This is fixed in the latest Node.js v14 but not in the latest v12.
