### ISSUE TITLE
Incorrect coverage reporting with throw in a block

### ISSUE THREAD

**Issue by Trott** [bcoe/c8#62] opened 2019-02-05 22:00 UTC
* **Version**: 11.9.0
* **Platform**: Darwin LIB-0F7FVH8-LT 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

In file `foo.js`:

```js
if (true) {
  throw new Error('foo');
}
```

I run this:

```bash
c8 node foo.js 
```

I get this output:

```console
/Users/trott/io.js/foo.js:2
  throw new Error('foo');
  ^

Error: foo
    at Object.<anonymous> (/Users/trott/io.js/foo.js:2:9)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |       50 |    66.67 |      100 |       50 |                   |
 foo.js   |       50 |    66.67 |      100 |       50 |               3,4 |
----------|----------|----------|----------|----------|-------------------|
```

What I expected:

I would not expect there to be a line 4 mentioned in the coverage report because the script is three lines long.
I would not expect line 3 to be mentioned as uncovered because there is nothing executable on it.
I would expect `Lines` to be covered 100% (but not `Branch`).

**Comment by thealjey** [comment] 2019-02-07 12:59
@Trott if you don't handle errors, how do you expect accurate results? the script terminates after that throw

**Comment by Trott** [comment] 2019-02-07 18:18
> @Trott if you don't handle errors, how do you expect accurate results?

Failing to catch the error is not the problem. I did that for simplicity. Here:

```console
$ cat foo.js
function doSomething(foo) {
  if (foo === 'throw') {
    throw new Error('foo');
  }
  console.log('Your foo is OK.');
}

try {
  doSomething('foo');
  doSomething('throw');
} catch (e) {
  console.log(`caught ${e}`);
}
$ c8 node foo.js
Your foo is OK.
caught Error: foo
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    92.86 |       80 |      100 |    92.86 |                   |
 foo.js   |    92.86 |       80 |      100 |    92.86 |                 4 |
----------|----------|----------|----------|----------|-------------------|
$ 
```

It is still incorrectly telling me that there is an uncovered **branch** when there is not. It is also still incorrectly reporting that line 4 is uncovered. Line 4 does not contain any executable code. Both branches of the `if` statement are being exercised. All errors are being caught.

**Comment by Trott** [comment] 2019-02-07 18:21
Incidentally, the `throw` isn't the problem _per se_. It appears that anything that returns control from the block will result in mis-reporting that the brace on a line by itself is uncovered.

```console
$ cat foo.js
function doSomething(foo) {
  if (foo === 'return') {
    return foo;
  }
  console.log('Your foo is OK.');
}

doSomething('foo');
doSomething('return');
$ c8 node foo.js
Your foo is OK.
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |       90 |       80 |      100 |       90 |                   |
 foo.js   |       90 |       80 |      100 |       90 |                 4 |
----------|----------|----------|----------|----------|-------------------|
$ 
```

**Comment by thealjey** [comment] 2019-02-08 08:06
I think this is a duplicate of #54

**Comment by bcoe** [comment] 2019-02-12 07:01
see: https://bugs.chromium.org/p/v8/issues/detail?id=8691&q=coverage%20throw&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Component%20Stars

**Comment by shinnn** [comment] 2019-04-08 21:25
Though the V8 bug referenced in https://github.com/bcoe/c8/issues/62#issuecomment-462640894 still seems unresolved, with Node.js v11.13.0 the code and command in https://github.com/bcoe/c8/issues/62#issue-406993534 works as expected now.

```console
$ node -v
v11.13.0

$ npx c8 node foo.js
/Users/Shinnosuke/foo.js:2
  throw new Error('foo');
  ^

Error: foo
    at Object.<anonymous> (/Users/Shinnosuke/foo.js:2:9)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 foo.js   |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by Trott** [comment] 2019-04-09 01:25
> Though the V8 bug referenced in [#62 (comment)](https://github.com/bcoe/c8/issues/62#issuecomment-462640894) still seems unresolved, with Node.js v11.13.0 the code and command in [#62 (comment)](https://github.com/bcoe/c8/issues/62#issue-406993534) works as expected now.

I believe @bcoe floated a fix in Node.js itself for the V8 that ships with Node.js.

**Comment by bcoe** [comment] 2019-04-09 01:44
@shinnn I believe things might start working once this patch is landed:

https://github.com/bcoe/c8/pull/74

**Comment by bcoe** [comment] 2019-10-24 05:44
this issue is corrected as of Node 13.

**Closed by bcoe** 2019-10-24 05:44 UTC
